### PR TITLE
Update captainhook to 5.1

### PR DESCRIPTION
**Pull request by cmmata**
Hi!

I have updated `composer.json` to allow `captainhook-validateauthor` use the new `captainhook v5.1`. I'm using this version in our development environment and seems to work so far without issues.

### CODE REVIEW

**Comment by shochdoerfer** [comment]
Thanks for the PR. Would you mind removing the PHP 7.2 and the nightly build from the Travis config?

**Comment by cmmata** [comment]
Removed! But I have just remembered PHP 7.3 is not the current stable. Do you want me to add the 7.4 build?

**Comment by shochdoerfer** [comment]
Yeah, sounds good. Thanks!

**Comment by cmmata** [comment]
Done! Tests passed in 7.3 and 7.4.

**Comment by shochdoerfer** [comment]
Awesome! Good job!

**Comment by shochdoerfer** [comment]
@cmmata version 0.2.0 just got released!

**Comment by cmmata** [comment]
Great! Thank you

**Pull request merged**
